/**
 * @file stream_init.cpp
 * @brief Configure, start, and release the CMSIS-Stream demo applications.
 *
 * This file connects generated schedulers to the shared CMSIS-Stream runtime.
 * It prepares hardware drivers, application parameters, event queues, execution
 * contexts, and the selected graph before handing execution to the runtime.
 */

/*
 
 
*/

// Application configuration file included in each generated scheduler.
// It contains application specific settings and include the header stream_runtime_config.hpp for
// CMSIS stream configuration settings.
#include "app_config.hpp"

// Parameters for application A
// Your application needs to provide this header and define a struct containing the settings
// used by your application A (a CMSIS Stream graph)
#include "appa_params.h"

// Those headers are generated by the python script describing the graph.
// The naming is defined in the python script and could be different from the naming used here.
// You can have several schedulers in case you may want to context switch between different graphs at runtime.
// If you have several scheduler, you must include the headers for each one.
#include "scheduler_appa.h"

// CMSIS Stream standard headers
#include "EventQueue.hpp"
#include "StreamNode.hpp"

// Runtime configuration settings
#include "stream_runtime_init.hpp"

#include "stream_init.hpp"


using namespace arm_cmsis_stream;


/**
 * @brief Index of the stream application currently selected for execution.
 *
 * Network 0 is the KWS graph. Network 1 is the camera/audio display graph.
 */
int currentNetwork = 0;

/**
 * @brief Array of stream execution contexts, one per network.
 */
stream_execution_context_t contexts[NB_APPS];

/**
 * @brief Event queues used by each stream application.
 */
EventQueue *queue_app[NB_APPS];

/*

 Pause all nodes in a given graph.

 Pause and resume helpers are not defined in the CMSIS-Stream module
 because the CStreamNode interface can be extended by the application and
 support new interfaces.

 To work with the CMSIS Stream module, two interfaces have been defined
 in cstream_node.h and the context_switch_intf is used in the
 pause / resume functions.

 Those functions are called by the CMSIS Stream Zephyr module which does not
 have any visibility on the application specific CStreamNode structure.

*/
static void pause_scheduler_app(const stream_execution_context_t *context)
{
    // Visit every identified node in the generated scheduler context.
    for (int32_t nodeid = 0; nodeid < (int32_t)context->nb_identified_nodes; nodeid++)
    {
        // The runtime stores nodes as opaque pointers; cast back to the app node type.
        CStreamNode *cnode = static_cast<CStreamNode *>(context->get_node_by_id(nodeid));
        if (cnode != nullptr)
        {
            // If the node implements the context switch interface, pause it
            if ((cnode->obj != nullptr) && (cnode->context_switch_intf != nullptr))
            {
                cnode->context_switch_intf->pause(cnode->obj);
            }
        }
    }
}

/*
 Resume all nodes in a given graph.
 This helper mirrors pause_scheduler_app().
*/
static void resume_scheduler_app(const stream_execution_context_t *context)
{
    // Visit every identified node in the generated scheduler context.
    for (int32_t nodeid = 0; nodeid < (int32_t)context->nb_identified_nodes; nodeid++)
    {
        // The runtime stores nodes as opaque pointers; cast back to the app node type.
        CStreamNode *cnode = static_cast<CStreamNode *>(context->get_node_by_id(nodeid));

        if (cnode != nullptr)
        {
            // If the node implements the context switching interface, resume it
            if ((cnode->obj != nullptr) && (cnode->context_switch_intf != nullptr))
            {
                cnode->context_switch_intf->resume(cnode->obj);
            }
        }
    }
}

/*

The get_scheduler_node functions cannot be used directly by the
CMSIS Stream module because they return an application dependent
CStreamNode* pointer. And potentially we could imagine having
different CStreamNodes structures for different graphs.
So we need to wrap them to return a void* pointer.

*/
static void *get_appa_node(int32_t nodeID)
{
    // Hide the application-specific node type behind the runtime's void* hook.
    return static_cast<void *>(get_scheduler_appa_node(nodeID));
}

static void *get_appb_node(int32_t nodeID)
{
    // Hide the application-specific node type behind the runtime's void* hook.
    return static_cast<void *>(get_scheduler_appb_node(nodeID));
}

/**
 * @brief Configure resources and start the currently selected stream graph.
 *
 * The startup sequence initializes optional hardware sources, fills the
 * hardware parameter block for each generated graph, allocates runtime memory
 * and event queues, initializes each scheduler, builds execution contexts, then
 * resumes and starts the graph selected by @ref currentNetwork.
 */
void stream_configure_and_start()
{
    int err;

    /*
    Step 1: configure hardware sources that may be shared by the stream graphs.


    */

    osEventFlagsId_t audioSrcEvent = 0;
    const vStreamDriver_t *audioSrcDriver = nullptr;

    osEventFlagsId_t videoSrcEvent = 0;
    const vStreamDriver_t *videoSrcDriver = nullptr;

#if defined(HAS_AUDIO_SRC)
    // Initialize the audio source driver when the build enables audio input.
    audioSrcDriver = init_audio_source(audioSrcEvent);

    if (audioSrcDriver == nullptr)
    {
        CMSISSTREAM_LOG_ERR("Error initializing audio source\n");
        goto error;
    }
#endif

#if defined(HAS_CAMERA_SRC)
    // Initialize the video source driver when the build enables camera input.
    videoSrcDriver = init_video_source(cg_interruptEvent);

    if (videoSrcDriver == nullptr)
    {
        CMSISSTREAM_LOG_ERR("Error initializing video source\n");
        goto error;
    }
#endif

    /*

    Step 2: fill generated parameter structures with application-specific data.

    */

    // App A needs to initialize its parameters.
    


    // Step 4: initialize the common CMSIS-Stream runtime memory.
    err = stream_init_memory();
    if (err != 0)
    {
        CMSISSTREAM_LOG_ERR("Error initializing stream\n");
        goto error;
    }

    // Step 5: allocate one event queue per graph.
    for (int network = 0; network < NB_APPS; network++)
    {
        queue_app[network] = stream_new_event_queue();

        if (queue_app[network] == nullptr)
        {
            CMSISSTREAM_LOG_ERR("Can't create CMSIS Stream Event Queue for network %d\n", network);
            goto error;
        }
    }

    // Step 6: initialize the generated schedulers and their graph nodes.
    // We may need to pass some parameters to the graph as argument to the init function
    // Those parameters are customizable in the Python script.
    // Here we assume that the generated scheduler requires an argument to have access to all
    // the parameters for the graph.
    // It could be a pointer to a struct and the struct may contain substructures with parameters for each node
    // of the graph that requires some customization or change of parameters at runtime.
    // Or we could also have a graph with no additional parameters

    err = init_scheduler_appa(queue_app[0], &appaParams);
    if (err != CG_SUCCESS)
    {
        CMSISSTREAM_LOG_ERR("Error: Failure during scheduler initialization for appa.\n");
        goto error;
    }

   

    // Step 7: bind generated scheduler callbacks and metadata to runtime contexts.
    // The defines are coming from the generated scheduler header.
    // Most of the functions here are also in the generated scheduler header but some of them are implemented 
    //in this file to hide application specific details from the CMSIS Stream module (like get_appa_node for example).

    contexts[0] = {
        .dataflow_scheduler = scheduler_appa,
        .reset_fifos = reset_fifos_scheduler_appa,
        .pause_all_nodes = pause_scheduler_app,
        .resume_all_nodes = resume_scheduler_app,
        .get_node_by_id = get_appa_node,
        .evtQueue = queue_app[0],
        .nb_identified_nodes = STREAM_APPA_NB_IDENTIFIED_NODES,
        .scheduler_length = STREAM_APPA_SCHED_LEN};


 /*

    Step 8: resume the selected graph and start the runtime threads.

    resume is called (like in a context switch) to allow
    the nodes to publish events before starting if they need to.
    event queue accepts events when resume is called.

    We cannot do it in init function of the node since in init we
    do not know if the graph is going to be run or if it is paused.

    If there is a need to distinguish start from resume then
    it has to be done in each node with a state variable.

    */
    resume_scheduler_app(&contexts[currentNetwork]);
    stream_start_threads(&contexts[currentNetwork]);

    return;
error:
    // Centralized error exit for failures during startup.
    CMSISSTREAM_LOG_ERR("Fatal error in main, stopping execution\n");

}

/**
 * @brief Stop all stream threads and release scheduler/runtime resources.
 */
void stream_free_all()
{
    // Wait for the runtime to stop before freeing graph-owned resources.
    stream_wait_for_threads_end();

    // Release resources allocated by the generated schedulers.
    free_scheduler_appa();

    // Destroy the event queues created during stream_configure_and_start().
    for (int network = 0; network < NB_APPS; network++)
    {
        delete queue_app[network];
    }

    // Release common CMSIS-Stream runtime memory last.
    stream_free_memory();
}
