version: 2.0.0
schedule-options:
  memory-optimization: true
  mem-strategy: independent_set
  buffer-allocation: true
code-generation-options:
  debug-limit: 1
  fifo-prefix: cv
c-code-generation-options:
  c-optional-args: "uint8_t *myBuffer,\n                              uint8_t *myBufferB"
  scheduler-c-file-name: cv_scheduler11

