# automatically generated by the FlatBuffers compiler, do not modify

# namespace: arm_cmsis_stream

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class IODesc(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 8

    # IODesc
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # IODesc
    def Id(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # IODesc
    def Nb(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateIODesc(builder, id, nb):
    builder.Prep(4, 8)
    builder.PrependUint32(nb)
    builder.PrependUint32(id)
    return builder.Offset()
