# Makefile for gcc compiler on Linux
CC = g++

INCLUDES = -I.
CFLAGS =  -pthread -fno-rtti -std=c++17 $(INCLUDES)

all:
	$(CC) -o simple $(CFLAGS) simple_scheduler.cpp  host_com.cpp cg_queue.cpp posix_thread.cpp  scheduler.cpp main.cpp

clean:
	rm -f ./simple
	