# Makefile for Xccode gcc compiler on Mac
XCodePath = $(shell xcode-select --print-path)
CC = $(XCodePath)/usr/bin/g++

INCLUDES = -I.
CFLAGS =  -pthread -fno-rtti -std=c++17 $(INCLUDES)

all:
	python create.py
	$(CC) -o simple $(CFLAGS) simple_scheduler.cpp host_com.cpp cg_queue.cpp posix_thread.cpp  scheduler.cpp main.cpp
	./simple

clean:
	rm -f ./simple
	