# Makefile for Xccode gcc compiler on Mac
XCodePath = $(shell xcode-select --print-path)
CC = $(XCodePath)/usr/bin/g++

INCLUDES = -I. -Iflatbuffers_1.23.2/include
CFLAGS =  -std=c++11 $(INCLUDES)

all:
	$(CC) -o runtime_mode $(CFLAGS) ./runtime_sched.cpp main.cpp 

clean:
	rm -f ./runtime_mode
	