# automatically generated by the FlatBuffers compiler, do not modify

# namespace: arm_cmsis_stream

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FIFODesc(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FIFODesc()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFIFODesc(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FIFODesc
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FIFODesc
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # FIFODesc
    def Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FIFODesc
    def Bufid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # FIFODesc
    def Delay(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # FIFODesc
    def Buffer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def FIFODescStart(builder): builder.StartObject(5)
def Start(builder):
    return FIFODescStart(builder)
def FIFODescAddId(builder, id): builder.PrependUint16Slot(0, id, 0)
def AddId(builder, id):
    return FIFODescAddId(builder, id)
def FIFODescAddLength(builder, length): builder.PrependUint32Slot(1, length, 0)
def AddLength(builder, length):
    return FIFODescAddLength(builder, length)
def FIFODescAddBufid(builder, bufid): builder.PrependUint16Slot(2, bufid, 0)
def AddBufid(builder, bufid):
    return FIFODescAddBufid(builder, bufid)
def FIFODescAddDelay(builder, delay): builder.PrependUint32Slot(3, delay, 0)
def AddDelay(builder, delay):
    return FIFODescAddDelay(builder, delay)
def FIFODescAddBuffer(builder, buffer): builder.PrependBoolSlot(4, buffer, 0)
def AddBuffer(builder, buffer):
    return FIFODescAddBuffer(builder, buffer)
def FIFODescEnd(builder): return builder.EndObject()
def End(builder):
    return FIFODescEnd(builder)