# automatically generated by the FlatBuffers compiler, do not modify

# namespace: arm_cmsis_stream

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UUID(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 16

    # UUID
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UUID
    def V(self): return [self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0 + i * 1)) for i in range(16)]
    # UUID
    def VLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(0))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # UUID
    def VIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(0))
        return o == 0


def CreateUUID(builder, v):
    builder.Prep(1, 16)
    for _idx0 in range(16 , 0, -1):
        builder.PrependUint8(v[_idx0-1])
    return builder.Offset()
