# Makefile for MSVC compiler on Windows
SHELL = cmd
CC = cl.exe
RM = del /Q /F

INCLUDES = /I.
WINFLAGS = /DWIN32 /D_WINDOWS /EHsc /Zi /Ob0 /Od /RTC1 -MDd 
CFLAGS =  $(INCLUDES) $(WINFLAGS)

all:
	$(CC) /Fecustomfifo.exe $(CFLAGS) ./scheduler.cpp main.cpp

clean:
	$(RM) main.obj
	$(RM) scheduler.obj 
	$(RM) customfifo.ilk 
	$(RM) customfifo.exe 
	$(RM) *.pdb 