var annotated_dup =
[
    [ "arm_cmsis_stream", null, [
      [ "cg_value", "group__cmsis__stream__generic__data.html#structarm__cmsis__stream_1_1cg__value", null ],
      [ "Descriptor", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1Descriptor", null ],
      [ "DistantDestination", "group__cmsis__stream__generic__data.html#structarm__cmsis__stream_1_1DistantDestination", null ],
      [ "Duplicate", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1Duplicate", null ],
      [ "Duplicate< IO, inputOutputSize, IO, inputOutputSize >", "classarm__cmsis__stream_1_1Duplicate_3_01IO_00_01inputOutputSize_00_01IO_00_01inputOutputSize_01_4.html", null ],
      [ "Duplicate< Shared< IO, inputShareStatus >, ioSize, Shared< IO, true >, ioSize >", "classarm__cmsis__stream_1_1Duplicate_3_01Shared_3_01IO_00_01inputShareStatus_01_4_00_01ioSize_00fd30238790b602e23c8e906d7caaabc7.html", null ],
      [ "Event", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1Event", null ],
      [ "EventOutput", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1EventOutput", null ],
      [ "EventQueue", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1EventQueue", null ],
      [ "FIFO", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1FIFO", null ],
      [ "FIFO< T, length, 0, 0 >", "classarm__cmsis__stream_1_1FIFO_3_01T_00_01length_00_010_00_010_01_4.html", null ],
      [ "FIFO< T, length, 0, 1 >", "classarm__cmsis__stream_1_1FIFO_3_01T_00_01length_00_010_00_011_01_4.html", null ],
      [ "FIFO< T, length, 1, 0 >", "classarm__cmsis__stream_1_1FIFO_3_01T_00_01length_00_011_00_010_01_4.html", null ],
      [ "FIFOBase", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1FIFOBase", null ],
      [ "GenericFromManyNode", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1GenericFromManyNode", null ],
      [ "GenericManyToManyNode", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1GenericManyToManyNode", null ],
      [ "GenericNode", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1GenericNode", null ],
      [ "GenericNode12", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1GenericNode12", null ],
      [ "GenericNode13", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1GenericNode13", null ],
      [ "GenericNode21", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1GenericNode21", null ],
      [ "GenericNode31", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1GenericNode31", null ],
      [ "GenericSink", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1GenericSink", null ],
      [ "GenericSource", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1GenericSource", null ],
      [ "GenericToManyNode", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1GenericToManyNode", null ],
      [ "IPC", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1IPC", null ],
      [ "ListValue", "group__cmsis__stream__generic__data.html#structarm__cmsis__stream_1_1ListValue", null ],
      [ "LocalDestination", "group__cmsis__stream__generic__data.html#structarm__cmsis__stream_1_1LocalDestination", null ],
      [ "MemServer", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1MemServer", null ],
      [ "Message", "group__cmsis__stream__generic__data.html#structarm__cmsis__stream_1_1Message", null ],
      [ "NodeBase", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1NodeBase", null ],
      [ "Pack", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1Pack", null ],
      [ "ProtectedBuffer", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1ProtectedBuffer", null ],
      [ "RawBuffer", "group__cmsis__stream__generic__data.html#structarm__cmsis__stream_1_1RawBuffer", null ],
      [ "Shared", "group__cmsis__stream__generic__data.html#structarm__cmsis__stream_1_1Shared", null ],
      [ "Shared< T, false >", "structarm__cmsis__stream_1_1Shared_3_01T_00_01false_01_4.html", null ],
      [ "SharedBuffer", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1SharedBuffer", null ],
      [ "StreamNode", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1StreamNode", null ],
      [ "Tensor", "group__cmsis__stream__generic__data.html#structarm__cmsis__stream_1_1Tensor", null ],
      [ "UniquePtr", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1UniquePtr", null ],
      [ "Unpack", "group__cmsis__stream__generic__data.html#classarm__cmsis__stream_1_1Unpack", null ],
      [ "ValueParse", "group__cmsis__stream__generic__data.html#structarm__cmsis__stream_1_1ValueParse", null ],
      [ "ValueParse< double >", "structarm__cmsis__stream_1_1ValueParse_3_01double_01_4.html", null ],
      [ "ValueParse< float >", "structarm__cmsis__stream_1_1ValueParse_3_01float_01_4.html", null ],
      [ "ValueParse< int16_t >", "structarm__cmsis__stream_1_1ValueParse_3_01int16__t_01_4.html", null ],
      [ "ValueParse< int32_t >", "structarm__cmsis__stream_1_1ValueParse_3_01int32__t_01_4.html", null ],
      [ "ValueParse< int64_t >", "structarm__cmsis__stream_1_1ValueParse_3_01int64__t_01_4.html", null ],
      [ "ValueParse< TensorPtr< T > >", "structarm__cmsis__stream_1_1ValueParse_3_01TensorPtr_3_01T_01_4_01_4.html", null ],
      [ "ValueParse< uint16_t >", "structarm__cmsis__stream_1_1ValueParse_3_01uint16__t_01_4.html", null ],
      [ "ValueParse< uint32_t >", "structarm__cmsis__stream_1_1ValueParse_3_01uint32__t_01_4.html", null ],
      [ "ValueParse< uint64_t >", "structarm__cmsis__stream_1_1ValueParse_3_01uint64__t_01_4.html", null ]
    ] ],
    [ "CMSISBufPoolAllocator", "group__cmsis__stream__cmsis__rtos__data.html#classCMSISBufPoolAllocator", "group__cmsis__stream__cmsis__rtos__data_classCMSISBufPoolAllocator" ],
    [ "CMSISEventPoolAllocator", "group__cmsis__stream__cmsis__rtos__data.html#classCMSISEventPoolAllocator", "group__cmsis__stream__cmsis__rtos__data_classCMSISEventPoolAllocator" ],
    [ "CMSISLock", "group__cmsis__stream__cmsis__rtos__data.html#classCMSISLock", null ],
    [ "CMSISMutex", "group__cmsis__stream__cmsis__rtos__data.html#classCMSISMutex", null ],
    [ "CMSISMutexPoolAllocator", "group__cmsis__stream__cmsis__rtos__data.html#classCMSISMutexPoolAllocator", "group__cmsis__stream__cmsis__rtos__data_classCMSISMutexPoolAllocator" ],
    [ "ContextSwitch", "group__cmsis__stream__cmsis__rtos__data.html#classContextSwitch", null ],
    [ "ContextSwitchInterface", "group__cmsis__stream__cmsis__rtos__templates.html#structContextSwitchInterface", null ],
    [ "CStreamNode", "group__cmsis__stream__cmsis__rtos__templates.html#structCStreamNode", null ],
    [ "MyQueue", "group__cmsis__stream__cmsis__rtos__data.html#classMyQueue", null ],
    [ "stream_execution_context_t_", "group__cmsis__stream__cmsis__rtos__data.html#structstream__execution__context__t__", null ],
    [ "StreamNodeInterface", "group__cmsis__stream__cmsis__rtos__templates.html#structStreamNodeInterface", null ]
];