# Makefile for Xccode gcc compiler on Mac
XCodePath = $(shell xcode-select --print-path)
CC = $(XCodePath)/usr/bin/g++

INCLUDES = -Igenerated -I../../Include/cg/src -I.
CFLAGS =  -std=c++11 $(INCLUDES)

all:
	$(CC) -o simple $(CFLAGS) generated/scheduler.cpp main.cpp

clean:
	rm -f ./simple
	