# Makefile for clang compiler on Mac
CC = clang

INCLUDES = -Igenerated -I../../Include/cg/src -I.
CFLAGS =  -std=c++11 $(INCLUDES)

all:
	$(CC) -o simple $(CFLAGS) generated/scheduler.cpp main.cpp

clean:
	rm -f ./simple
	