version: 1.1.0
code-generation-options:
  debug-limit: 1
  scheduler-name: dynamic_scheduler
  fifo-prefix: dynamic_
c-code-generation-options:
  c-optional-args: []
  scheduler-c-file-name: dynamic_scheduler

